spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/laboris_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

api.security.token.secret=OoIkGTG6kpSDZNcuFKr2+dHKtA9ZjnUJcI1MU6Ie2Eo=
google.maps.api.key=AIzaSyBDTgT8h3goJyMhHyK7cx7-wKEDBgLuYHY
