spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/laboris_db
spring.datasource.username=''
spring.datasource.password=''
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

api.security.token.secret=''
google.maps.api.key=''
api.resend.key=''
