spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/laboris_db
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

api.security.token.secret=${TOKEN_SECRET}
google.maps.api.key=${GOOGLE_MAPS_KEY}
api.resend.key=${RESEND_KEY}
